# Railway Configuration for Backend Companion Service
[build]
  builder = "NIXPACKS"
  buildCommand = "cd components/activity-logger/companion && npm install"

[deploy]
  startCommand = "cd components/activity-logger/companion && node src/index.js"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[[services]]
  name = "companion-service"
  
  [services.env]
    PORT = "43917"
    HOST = "0.0.0.0"
    NODE_ENV = "production"

