/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Diff result structure */
export interface DiffResult {
  diffSize: number
  isSignificant: boolean
  summary: string
  linesAdded: number
  linesRemoved: number
  charsAdded: number
  charsDeleted: number
  afterContent: string
  unifiedDiff?: string
}
/** Line change information */
export interface LineChange {
  lineNumber: number
  changeType: string
  content: string
}
/** File statistics */
export interface FileStats {
  lines: number
  chars: number
  words: number
  blankLines: number
  commentLines: number
}
/**
 * Calculate diff between two text strings
 *
 * This is 5-10x faster than the JavaScript 'diff' library
 * Uses the 'similar' crate which implements Myers' diff algorithm in Rust
 *
 * @param text1 - Original text
 * @param text2 - Modified text
 * @param threshold - Minimum change size to be considered significant
 * @param include_unified - Whether to include unified diff format
 * @returns DiffResult with detailed change information
*/
export declare function calculateDiff(text1: string, text2: string, threshold?: number | undefined | null, includeUnified?: boolean | undefined | null): DiffResult
/**
 * Get detailed line-by-line changes
 * Useful for showing exact changes in the UI
*/
export declare function getLineChanges(text1: string, text2: string): Array<LineChange>
/**
 * Calculate file statistics
 * Fast analysis of code files
*/
export declare function calculateFileStats(content: string): FileStats
/**
 * Batch diff calculation for multiple files
 * Uses parallel processing with Rayon for maximum performance
 *
 * This can process hundreds of files simultaneously
*/
export declare function batchCalculateDiffs(pairs: Array<[string, string]>, threshold?: number | undefined | null): Array<DiffResult>
/**
 * Fast text search with multiple patterns
 * Uses parallel regex matching for speed
*/
export declare function searchPatterns(content: string, patterns: Array<string>): Record<string, number>
/**
 * Detect language from file content
 * Fast heuristic-based language detection
*/
export declare function detectLanguage(content: string, filename?: string | undefined | null): string
/**
 * Calculate similarity between two texts
 * Returns a ratio between 0.0 (completely different) and 1.0 (identical)
*/
export declare function calculateSimilarity(text1: string, text2: string): number
/**
 * Extract function signatures from code
 * Fast parsing for common languages
*/
export declare function extractFunctions(content: string, language: string): Array<string>
/**
 * Fast deduplication of large text arrays
 * Uses fast hashing for O(n) performance
*/
export declare function deduplicateStrings(strings: Array<string>): Array<string>
/**
 * Calculate token count estimate
 * Fast approximation without calling external APIs
*/
export declare function estimateTokens(text: string): number
